# permissions for end users to view ansiblewelcomepages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansiblewelcomepage-viewer-role
rules:
  - apiGroups:
      - welcome.ansible.com
    resources:
      - ansiblewelcomepages
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - welcome.ansible.com
    resources:
      - ansiblewelcomepages/status
    verbs:
      - get
